### ISSUE TITLE
Use workflow variables to migrate settings to new versions

### ISSUE THREAD

**Issue by birnstiel** [caleb531/open-conference-url#12]
Feature request: Settings are overwritten with every new install. It might be possible to store the settings as [workflow variables](https://www.alfredapp.com/help/workflows/advanced/variables/) instead of in a file that ships with the workflow. This way they will be migrated to new versions automatically.

**Comment by caleb531** [comment]
@birnstiel Making the preferences persist across installs is definitely something I'd like to do. However, I have identified a potential downside. Please see my breakdown below and let me know your thoughts:

## Option 1: Using workflow variables

### Pros

1. We would be using the standard Alfred mechanism for storing and persisting preferences, which is great for everyone

### Cons

1. Because workflow/environment variables only support string values, complex structures like the `conference_domains` array would need to be expressed as a comma-delimited list (e.g. `zoom.us,meet.google.com,hangouts.google.com,uberconference.com,teams.microsoft.com,gotomeeting.com,webex.com`, which feels pretty unwieldy)

## Option 2: Workflow Data Directory

An alternative approach would be to move `prefs.json` to Alfred's non-volatile Workflow Data directory under `~/Library/Application Support/Alfred/Workflow Data/`

### Pros

1. The entire JSON schema and structure of the workflow preferences are preserved, so it stays readable and easily editable

### Cons

1. The downside to this approach is that the aforementioned directory is not very discoverable or quickly navigable.

## Thoughts?

So.. what are your thoughts on these pros/cons?

**Comment by birnstiel** [comment]
I think the first options is a bit less convenient than I hoped for, but I still prefer it. I think you cover most video conference urls, only for zoom, you might need to change the string to allow all zoom urls. Many urls include the company/institution in the domain, like `my-university.zoom.us` which is currently missed. If this is fixed, most people won't have to change the settings and if they do, appending to a comma-separated list seems doable, especially since one can see already how it's done.

**Comment by birnstiel** [comment]
not really - it would match a location of `https://myuniversity.zoom.us/j/...`, but not `https://my-university.zoom.us/j/...`.

**Comment by caleb531** [comment]
@birnstiel Ah, that's my mistake. I'm only matching `\w` for the subdomain part, which does not include dashes. I've corrected that now on my `v4` branch (which will contain all of the upcoming new features and fixes for the workflow).

If you'd like to get this fix right away, run the following:

```sh
git fetch
git checkout v4
awp # assumes you have set up the virtualenv and installed alfred-workflow-packager
```

**Comment by caleb531** [comment]
@birnstiel I just released v4.0.0-beta.1 with the new Workflow Variables system. Can you please test it out, and let me know how it works for you? Thanks in advance!

https://github.com/caleb531/open-conference-url/releases/tag/v4.0.0-beta.1

**Comment by birnstiel** [comment]
seems to work - all zoom links I tested are now found. Thanks for fixing this!

**Comment by caleb531** [comment]
@birnstiel My pleasure! I just released v4 stable with this new Workflow Variables system for setting preferences, so I think it's safe to close the issue. If you run into any trouble, please create a new issue.

https://github.com/caleb531/open-conference-url/releases/tag/v4.0.0
