### ISSUE TITLE
Applescript taking a considerable time

### ISSUE THREAD

**Issue by tiems90** [caleb531/open-conference-url#16]
Hi!

I've been using this workflow for a while and love it. Recently, I've noticed the workflow timing out before it can return values.
This seems to be tied to the applescript. With corporate calendars syncing, it is quite a big of total events in the calendar. 

For example, just running the apple script  by itself takes `1:40` min. 
Meanwhile, `icalBuddy eventsToday` sits at around `3.5` seconds. 

Any thoughts on what might be causing that performance in the apple script, or if it is worth forking and reworking it into a fork for myself, if it does not affect others?

**Comment by caleb531** [comment]
@tiems90 This is interesting. Personally, I found the execution time of the AppleScript to be comparable with icalBuddy's execution time.

To give you some context: in [v4.0.0](https://github.com/caleb531/open-conference-url/releases/tag/v4.0.0), I replaced icalBuddy with AppleScript in order to work around a permissions issue identified in #11. Because I found the performance difference to be unnoticeable, I thought the AppleScript could achieve the best of both worlds—avoiding the pesky permission problems without sacrificing performance.

But I can see how the AppleScript might not be as scalable in practice. If you have the time and skill to implement a potential alternative, I am all for it. I would love to see what improvements you might be able to find (unless you imply that your rework would simply be reverting back to icalBuddy).

**Comment by tiems90** [comment]
Yeah, I did not run into any issues until very recently; so I'm wondering if it is just an additional calendar that got synced that is causing the issues here. 

I've reverted reverted to [v3.0.1](https://github.com/caleb531/open-conference-url/releases/tag/v3.0.1) to test, and tried to work around the permissions issue by simply installing icalBuddy through home-brew and referencing the system-provided icalBuddy. That seems to at least solve most issues at this point, but it's obviously not a suitable general solution.

I'll have a look and see if I can find another way of tackling this! (In the meantime with a downgrade, at least I have my beloved workflow back!)

**Comment by caleb531** [comment]
Good afternoon, @tiems90—just wanted to check in to ask if you've made any additional discoveries with possible performance improvements to the AppleScript.

**Comment by tiems90** [comment]
Hey @caleb531! 

I've been exploring some options, but I wasn't able to find real improvements on the AppleScript side. I've explored some alternatives, but they all run into the same issues that triggered the migration to the AppleScript in the first place.

**Comment by caleb531** [comment]
@tiems90 Fair enough! It's worth noting that OCU now has support for specifying which calendars you want to fetch (via #19). This functionality was released recently as part of v5.2.0 of the workflow, so please have a look in case that helps at all:

https://github.com/caleb531/open-conference-url/releases/tag/v5.2.0

**Comment by tiems90** [comment]
Oh! That looks very promising! I think the main issue has been my various company-wide work calendars that come filled with events. Let me check the latest version!

**Comment by tiems90** [comment]
Quick update! In the end I just cleaned up my calendar of historic events which sped it up drastically. The big difference between the apple script and icalbuddy just seems to be the speed as it loops through events; it didn't become an issue until it hits 10K-ish historic events it's going through.

**Comment by caleb531** [comment]
@tiems90 Gotcha! In that case, I think I'm going to close this issue since we've explored many alternative solutions without any tangible results. But I am glad you were able to speed up the workflow by clearing out old events!

If you have any performance ideas in the future, feel free to post here and I'll reopen the issue.

**Comment by tiems90** [comment]
Absolutely! And thanks again for the workflow, it really is such a great productivity tool! 😄
