### ISSUE TITLE
Stuck in "Loading..." state when accessing meetings

### ISSUE THREAD

**Issue by calvinwyoung** [caleb531/open-conference-url#30]
I'm trying to use the workflow but can't seem to get it to load any meetings. This is what I've done:

- Installed workflow from [Alfred Gallery](https://alfred.app/workflows/caleb531/open-conference-url/)
- Used the default configurations
- Typed `conf` in Alfred
- I never get past the "Loading..." message
![image](https://github.com/caleb531/open-conference-url/assets/1173768/3ac5c383-e732-4eb7-b3b5-49d41a5cc9d9)

- This is all that shows up in the debugger:
![image](https://github.com/caleb531/open-conference-url/assets/1173768/ef6b0fff-a0d6-4bff-af15-9a5b4c0c2bb6)

More details that may or may not be helpful:
- I'm using Alfred v5.1.4 and Sonoma 14.0
- If I run `/usr/bin/python3 -m ocu.list_events` in my terminal, I get the following error, which makes me think something didn't get installed correctly:
```bash
/Library/Developer/CommandLineTools/usr/bin/python3: Error while finding module specification for 'ocu.list_events' (ModuleNotFoundError: No module named 'ocu')
```

Is there any other information I can provide to help debug this?

**Comment by caleb531** [comment]
@calvinwyoung Hm, interesting. Two things:

1. Can you run `python3 --version` and tell me what version you're on? It should be around 3.9.6, since I am also using Alfred 5.1.4 with macOS Sonoma
2. Can you please send me a screenshot of the directory tree for the workflow? Preferably in column view or something like that. It should look like this:

<img width="920" alt="Screenshot 2024-01-29 at 6 41 12 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/337f2d1a-b350-4ed9-ac55-7ff99b7b8a6a">

**Comment by calvinwyoung** [comment]
@caleb531 Thanks for the quick response

1. `/usr/bin/python3 --version` returns `Python 3.9.6`
2. Here's the screenshot you requested:
<img width="722" alt="image" src="https://github.com/caleb531/open-conference-url/assets/1173768/726a271f-40b2-47ef-b0d9-9d017a639be4">

Though I wonder if the issue is that I'm using pyenv to manage my Python environment. `which python` returns `/Users/calvin/.pyenv/shims/python`. Is it possible that pyenv is somehow conflicting with the system Python that the workflow's using?

**Comment by caleb531** [comment]
@calvinwyoung The original error message you provided indicates that the python3 binary being used is `/Library/Developer/CommandLineTools/usr/bin/python3`, unless `pyenv` or some other process somehow modified that binary. I wonder if reinstalling the Apple Command Line Tools would help:

```sh
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by calvinwyoung** [comment]
@caleb531 I followed those instructions and reinstalled Apple Command Line Tools. Unfortunately I'm still running into the same error :(

Is there anything else can I try as a troubleshooting step?

**Comment by caleb531** [comment]
@calvinwyoung Oh wait a minute.. I think I misinterpreted the initial error message you provided. The command:

```
/usr/bin/python3 -m ocu.list_events
```

Will only work from the workflow directory (i.e. that one you screenshotted for me). I tried running the same command from my home folder and received exactly the same error message:


> /Library/Developer/CommandLineTools/usr/bin/python3: Error while finding module specification for 'ocu.list_events' (ModuleNotFoundError: No module named 'ocu')

Even if you get past this error, you will probably run into a `KeyError: 'use_icalbuddy'` error because the workflow configuration's environment variables haven't been loaded in that context.

With that, I think the actual issue might be a performance issue. If you have an especially large number of events across all your calendars, the workflow can take longer to run. There are a few solutions to this:

1. _Recommended:_ Install icalBuddy (`brew install ical-buddy`) and enable the icalBuddy integration in the OCU workflow settings. Then try invoking `conf` again
    <img width="449" alt="Screenshot 2024-01-31 at 3 38 31 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/77c6a463-50fa-42c1-a777-8a962db68580">
2. Alternatively, you could specify the name of a calendar that has fewer events, just to see if this is a performance issue.
    <img width="404" alt="Screenshot 2024-01-31 at 3 39 18 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/a58cb0cf-d12b-4259-8fa5-5fa321d817b0">

**Comment by calvinwyoung** [comment]
@caleb531 yup specifying a calendar with fewer events solved this issue for me. Thanks for the additional info!

**Comment by caleb531** [comment]
@calvinwyoung Great great! With that, I will close this issue now that your performance trouble has been resolved.
