### ISSUE TITLE
Queing argument: Null

### ISSUE THREAD

**Issue by skobylite** [caleb531/open-conference-url#31]
Hey - I'm getting the following error:
[09:27:33.412] Open Conference URL[Script Filter] Queuing argument '(null)'

- I've tried zoom and google meet as the calendar event URL
- alfred 5 has full calendar permissions
- Event is within 20 minutes

Do you have any suggestions on how to troubleshoot? Thanks in advance!

**Comment by caleb531** [comment]
@skobylite Well, in my testing, I also receive the `Queuing argument '(null)'` line, which makes sense because the `conf` command doesn't accept any arguments. So I don't regard that as being the issue.

A few ideas for troubleshooting, and a few questions about what you're experiencing:

1. What version of the workflow are you on? I might recommend re-installing [the latest v7.1.4 workflow](https://github.com/caleb531/open-conference-url/releases/tag/v7.1.4) to ensure you haven't accidentally broken it
    <img width="855" alt="Screenshot 2024-03-31 at 3 59 58 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/4fe0a283-56ec-4815-9a25-094984fda82f">

2. When you run `conf`, are you seeing "Loading..."? Or are you seeing the "No Results" message?
    <img width="594" alt="Screenshot 2024-03-31 at 4 03 13 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/6d3a16e6-b92b-4813-b373-b255021ab547">
    <img width="597" alt="Screenshot 2024-03-31 at 4 03 29 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/0ab69d6f-2975-4160-be6b-5f9cb95352dd">
    If you see the "Loading..." message but never see the "No Results" message, this may be an indication that your calendars have a lot of events and are taking a long time to load; if you suspect this might be the case, I would highly recommend trying the workflow's built-in icalBuddy integration ([instructions here](https://github.com/caleb531/open-conference-url?tab=readme-ov-file#use-icalbuddy))

3. If you see no rows at all in Alfred, or you see the fallback search results (like Google, Amazon, etc.), then that is indicative of a workflow error. If this is the case, then you should be seeing more logs in the console than the first line you provided. But if the last line you see _is_ the one you provided, then I'm guessing the issue falls into one the categories I've mentioned above
    <img width="611" alt="Screenshot 2024-03-31 at 4 06 49 PM" src="https://github.com/caleb531/open-conference-url/assets/872474/5232178a-990e-4950-8543-1aa13b55fb2e">

**Comment by caleb531** [comment]
@skobylite Did any of the above troubleshooting steps work for you? Please let me know!

**Comment by Avivbens** [comment]
Same thing here 1️⃣ 

I'll be glad to have an update 🙏

**Comment by caleb531** [comment]
@Avivbens @skobylite Did any of the above troubleshooting steps work for you? What version of the workflow are you each using? It would really help me to help you guys.

**Comment by caleb531** [comment]
@Avivbens @skobylite Just checking in—can you please provide feedback on any of the above troubleshooting steps?

**Comment by Avivbens** [comment]
> @Avivbens @skobylite Just checking in—can you please provide feedback on any of the above troubleshooting steps? 

I do see this, but seems that the workflow works just fine for me…
So, for now, I think that no action is needed 👍✨
