### ISSUE TITLE
Join next meeting via Hotkey?

### ISSUE THREAD

**Issue by jamie9090** [caleb531/open-conference-url#33]
Hey there!

I would love to be able to join the next meetings conference via a Hotkey.

Apps like Notion Calendar (Cron Calendar) allow this via CMD + SHIFT + J.

Not sure if this possible, but would love it if so.

Cheers!

**Comment by caleb531** [comment]
@jamie9090 In theory, this should be possible, but it may be a strange user experience—it takes a second or two for the script to load calendar events, so you may not get any immediate feedback.

But one thing you could do is attach a hotkey object to the "Show Alfred" workflow object (where the workflow object is configured to show the "conf" keyword in Alfred). Of course, you would need to press the Enter key once the results come up, but this should be a small extra step.

I would recommend creating this as a separate workflow so that the main OCU workflow can still receive updates without overwriting your hotkey changes. At any rate, here's a bare-bones workflow to give you an idea of how this could work—feel free to modify and extend it.

[Open Conference URL Hotkey.zip](https://github.com/user-attachments/files/17534741/Open.Conference.URL.Hotkey.zip)
