### ISSUE TITLE
python2 not available on latest macOS 

### ISSUE THREAD

**Issue by birnstiel** [caleb531/open-conference-url#8]
the calls to `/usr/bin/python2` should be changed to `/usr/bin/python3` on the latest os.

**Comment by davidawad** [comment]
I was just about to comment here not sure why this plugin stopped working (I DEEPLY love this plugin). 

I wouldn't have thought to look for a python installation so thank you @birnstiel for sharing this note. 

I followed this guide to get python2 installed. 

• https://stackoverflow.com/questions/60298514/how-to-reinstall-python2-from-homebrew 

Then I ran this command to get my python2 back (specifically for this alfred plugin) 
`sudo ln -s /usr/local/bin/python2 /usr/bin/python2`

for your information you'll need to disable system integrity protection in order to make the symlink to the python2 install though. 

`sudo csrutil disable`

**Comment by caleb531** [comment]
@birnstiel @davidawad My sincere apologies for the delay, guys. Apparently, this was the _one_ repository I wasn't receiving notifications on. smh...

I released v3.0.0 a couple days ago with the fix for python3. You guys are correct — swapping out `/usr/bin/python` for `/usr/bin/python3` should do the trick, since the rest of the workflow code is already python2/python3 compatible.

Please try OCU v3 and let me know how it works for you:
https://github.com/caleb531/open-conference-url/releases/tag/v3.0.0

**Comment by caleb531** [comment]
@birnstiel @davidawad Hey, guys! Just wanted to check up if my v3.0.0 release fixes the issue so I can close this ticket.

**Comment by birnstiel** [comment]
Yes, this part is fixed. However initially, the workflow didn't run since `icalBuddy` is not from a trusted developer. The workaround was to open the workflow in the finder (right-click on it in the list -> Open in Finder), go into `ocu`, right-click `icalBuddy` and select `Open` - this allows me to run it despite this security warning. Possibly use a homebred-installed version first and fall back to the included version second. Another feature request would be to store the settings that are currently in `prefs.json` in as [workflow variables](https://www.alfredapp.com/help/workflows/advanced/variables/) - this way they will be migrated to new versions automatically. But that's just FYI, feel free to close this issue and thanks for fixing it!

**Comment by caleb531** [comment]
@birnstiel Thanks for this! I would need to confirm if Homebrew-installed `icalBuddy` actually bypasses the security dialog, but I understand the value. As for the workflow variables, that's a great idea, I will work on it.

It would be great if you could please create new GitHub issues for both of these feature requests so they can have their own threads for discussion.
